apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: data
spec:
  type: state.azure.cosmosdb
  version: v1
  metadata:
  - name: url
    value: "true"
  - name: database
    value: "orders"
  - name: collection
    value: "data"
  